name: "Checkout Repository"

inputs:
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    default: 1
  gh-token:
    description: "GitHub token for checkout repo."
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.gh-token }}